name: Cole's Coffeelog
pygments: true
exclude: ["sync.sh", "README.md"]
mini_magick:
    thumbnail:
        source: images/original
        destination: images/thumbnails
        resize: "100x100"
    posts:
        source: images/original
        destination: images/posts
        resize: "600x600"